## 0 导入 numpy

In [2]:
import numpy as np

## 1 array 的属性
+ shape: array 的形状,一个元组

+ size: array 的尺寸，shape 的所有元素之积

+ ndim: array 的维数

+ dtype: array 数据类型

    np 将 `int` 细分为了 `np.int8`,`np.int16`,...,`np.int128`；将 `float` 细分为了 `np.float16`,`np.float32`,...,`np.foat256`等.

+ itemsize: array 每个元素的字节数

## 2 创建 array
np 数组的类型是 `np.ndarray`。此笔记将 np 数组简称为 array。

In [3]:
type(np.array([1]))

numpy.ndarray

### 2.1 np.array
`np.array` 可以将一个列表或元组转为一个 array

In [4]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

### 2.2 np.asarray
`np.array()` 是一个将输入数据（如列表、元组等）复制为一个新的 array 的函数。`np.asarray()` 也将输入转换为数组，但当输入数据已经是一个  array 时，它不会复制数据，而是直接返回该数组。因此，array 的类型转换更推荐使用 `np.asarray()`。

In [5]:
arr_asarray = np.asarray(arr)
arr_array = np.array(arr)

print(arr is arr_array)  # False，因为np.array()复制了数据
print(arr is arr_asarray)  # True，因为np.asarray()没有复制数据


False
True


注意：

+ 当使用 `np.asarray()` 函数将 Pillow 图像对象转换为 array 时，默认情况下，结果数组的内存是不可写的。

### 2.3 np.arrange

`np.arrrange` 的作用与 `range` 类似

In [6]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### 2.5 np.linspace
创建从起点到终点的等分（默认包含起点和终点），有点像arange的连续版本。

**参数**

+ `start`: 起点

+ `stop`: 终点

+ `num`: 点的个数

+ `endpoint`: bool 值,指定是否包含终点(是否包含终点并不影响点的个数)

In [7]:
np.linspace(0,5,4,endpoint=False)

array([0.  , 1.25, 2.5 , 3.75])

### 2.6 指定为全0或全1
以 `np.ones()` 为例，参数为 `shape`，指定 array 的形状。

In [8]:
np.ones((3,2)),np.zeros((3,2))

(array([[1., 1.],
        [1., 1.],
        [1., 1.]]),
 array([[0., 0.],
        [0., 0.],
        [0., 0.]]))

### 2.7 np.empty
`np.empty()` 只分配内存而不初始化值，所以值是随机的。(在 `.py` 脚本下运行确实是随机值，不知道是不是 jupyter 是不是有什么特性，初始化的值全为 0)

参数为 `shape` ，指定 array 的形状。

In [9]:
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

## 3 保存 array
### 3.1 np.savetxt
`np.savetxt` 将 array 保存为 `txt` 或者 `csv` 文本文件。

**参数**

+ `fname`: 保存的文件名

+ `X`: array

+ `delimiter`: 分隔符

+ `fmt`: 格式


In [10]:
np.savetxt("save.txt",arr,delimiter=",",fmt="%f")

### 3.2 np.save()
`np.save()` 将 array 保存为 `.npy` 格式的文件，这种格式是专门用来存 array 的二进制文件。

In [11]:
np.save("test.npy",arr)

## 4 导入 array

### 4.1 np.loadtxt
`np.loadtxt` 可以读入一个 `txt` 或者 `csv` 文本文件。文件的不同行将会被读成 array 的不同行。

**参数**

+ `delimiter`: 分隔符

+ `encoding`: 编码方式

+ `dtype`: 类型

In [12]:
np.loadtxt("test.txt", delimiter=',',encoding="utf-8",dtype=np.int32)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### 4.2 np.fromfile()
`np.loadtxt()` 的加强版。可以从文本文件或二进制文件中读取数据并将其转换为 array。

**参数**

+ file：要读取的文件的名称或文件对象。如果是文件名称，该文件将会被打开；如果是文件对象，则从当前位置开始读取。
+ dtype：数据的数据类型。这决定了返回的数组中元素的类型。默认值是float。
+ count：要读取的元素数量。默认为-1，表示读取文件中的所有数据。
+ sep：如果是从文本文件读取数据，sep参数定义了分隔符。默认为空，意味着函数期望读取二进制文件。如果提供了分隔符（例如，逗号,或空格 ），则表示从文本文件中读取数据。

In [13]:
np.fromfile("test.txt",sep=",")

C:\Users\lm\AppData\Local\Temp\ipykernel_7348\2785885426.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromfile("test.txt",sep=",")


array([1., 2., 3., 4.])

这里有点问题，这个函数好像无法正确处理 `\n`。读文本文件还是先用 `loadtxt` 吧

### 4.3 np.load()
`np.load()` 读取一个 `.npy` 文件


In [14]:
np.load("test.npy")

array([[1, 2, 3],
       [4, 5, 6]])

## 5 拼接

### 5.1 np.vstack()
`np.vstack()` 的作用是垂直堆叠一些 array.

**参数**

+ `tup`: 这些 array 被包装在一个元组里传入（传一个列表也行）


In [15]:
row1=np.ones(3)
row2=np.ones(3)*2
np.vstack((row1,row2))

array([[1., 1., 1.],
       [2., 2., 2.]])

### 5.2 np.hstack()
`np.hstack()` 的作用是水平堆叠一些 array.

**参数**

+ `tup`: 这些 array 被包装在一个元组里传入（传一个列表也行）

In [16]:
col1=np.ones(3)
col2=np.ones(3)*2
np.hstack((col1,col2))

array([1., 1., 1., 2., 2., 2.])

## 6 数学运算

+ 累积乘积：输入和输出的 shape 是一致的。

In [17]:
a=np.arange(1,4)        # [1, 2, 3]
np.cumprod(a)           # [1, 1*2, 1*2*3]


array([1, 2, 6])